[package]
name = "maze-rs"
version = "0.5.0"
authors = ["fiburonsk <10441670+fiburonsk@users.noreply.github.com>"]
edition = "2018"

[dependencies]
rand = "0.7.2"
image = "0.22.2"

[[bin]]
name = "maze"
path = "src/main.rs"
