[package]
name = "maze-rs"
version = "0.9.1"
authors = ["fiburonsk <10441670+fiburonsk@users.noreply.github.com>"]
edition = "2018"

[dependencies]
rand = "0.8"
argh = "0.1.3"
image = { version = "0.24", default-features=false, features=["png"] }

[[bin]]
name = "maze"
path = "src/main.rs"
