[package]
name = "maze-rs"
version = "0.9.0"
authors = ["fiburonsk <10441670+fiburonsk@users.noreply.github.com>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
argh = "0.1.3"

[dependencies.image]
version = "0.22.5"
features = ["png"]

[[bin]]
name = "maze"
path = "src/main.rs"
